name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        persist-credentials: false # Explicitly disable persistent credentials

    - name: Set up GitHub token
      run: git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/happy1511/PortFolio-React.git

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Debug Info - List files
      run: ls -la

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        persist-credentials: false # Explicitly disable persistent credentials

    - name: Set up GitHub token
      run: git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/happy1511/PortFolio-React.git

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: ./build

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Debug Info - List files
      run: ls -la ./build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
